# Generated by Django 3.2.8 on 2021-12-06 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211206_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200, verbose_name='Job')),
                ('email_csv', models.CharField(max_length=200, verbose_name='Email')),
                ('domain_name', models.CharField(max_length=200, verbose_name='Domain name')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Phone number')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company name')),
                ('text', models.CharField(max_length=1000, verbose_name='Text')),
                ('integer', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Integer')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('data', models.DateField(auto_now=True, verbose_name='Data')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='User name'),
        ),
    ]
