# Generated by Django 3.2.8 on 2021-12-06 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211206_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_data',
            name='fullname',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csv_data',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='csv_data',
            name='email_csv',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
    ]
